# Main configuration for the scanner.
# Tweak timeouts and booleans for your environment.

headless: true                      # default run headless
nav_timeout_ms: 60000               # navigation timeout in ms
wait_after_load: 1.0                # seconds to wait after page load
screenshot_dir: "outputs/screenshots"
output_dir: "outputs"
reports_dir: "outputs/reports"
logs_dir: "outputs/logs"
max_elements: 2000
pre_actions_enabled: true
allow_manual_human_check: true
session_state_path: "outputs/storage_state.json"
crawl_max_depth: 2
retry_attempts: 3
retry_delay_seconds: 3
retry_backoff: true                 # exponential backoff between retries
after_interact_delay: 0.8
validation_detect_seconds: 1.0
element_query_timeout_ms: 3000

llm:
  provider: "ollama"
  ollama_model: "llama3.1:8b"
  ollama_endpoint: "http://127.0.0.1:11434/api/generate"
  timeout: 120
  max_retries: 2

canvas:
  enable_hook: true
  enable_ocr: true                  # set true if Tesseract installed

stealth:
  enable: true
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36"

log_rotation_keep: 10               # number of log files to keep
knowledge_max_entries: 5000         # auto-trim knowledge DB beyond this
